debug: 1
# location: SE10 8XJ
keyboard_trigger: 0
media_player: false
network:
  max_retries: 10
google_logging:
  # credentials_file: development
  sheet_id: 1L8arTDLJPEf_1JPNVlUn25ykLgOh4MmRFd5z42QWCms
text_logging: true
gps_sensor: true
servo_motor: false
midi_controls:
  sensitivity: 10
  sensitivity_seconds: 10
  servo_angle: 11
  angle_multiplier: 90
  servo_on_ctrl: 91
  servo_on_time: 1
relay_output:
  gpio_pin: 24
  on_time: 6
switch_input:
  gpio_pin: 23
